path: '/workspace/wordpress'
url: 'http://local.divi-dev.site'
user: etdev
debug: false
allow-root: true
core config:
  dbhost: localhost
  dbname: wordpress
  dbuser: root
  dbpass: password
  extra-php: |
    define( 'WP_DEBUG', true );
    define( 'WP_DEBUG_LOG', true );
